### ISSUE TITLE
plan for reviewing pull requests

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-metadata-old#14]
Need a plan for reviewing @jacobthill pull requests which will consist of harvesting scripts and metadata mainly.

**Comment by jacobthill** [comment]
Have a tentative plan that @peetucket or @anarchivist will review data and harvesting related pull requests and the traject related pull requests, which are currently in the dlme repo will be reviewed by developers working on this dev cycle. Will need to decide on long term strategy once the traject files are moved into the dlme-metadata repo and dev team moves on to another project.

**Comment by peetucket** [comment]
We can also discuss at Monday's planning meeting
