### ISSUE TITLE
Change bnf config files cho_type to cho_edm_type

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-metadata-old#18]

**Comment by jacobthill** [comment]
Changed from cho_has_type to cho_type. I'm still a bit confused about why there are three type categories and what the difference is between them. cho_edm_type seems like the starting point but is does not cover things like cartographic, software, multimedia, etc. Do we still need it? There also might be some value in sub dividing these type categories e.g. image -> stamp, photo, painting, postcard, etc. It adds complexity but given that normalization/authority control for names, dates, etc. will be complicated, type might be the most valuable facet from a UX standpoint

**Comment by anarchivist** [comment]
It's probably worth looking at the [application profile](https://github.com/sul-dlss/dlme/blob/master/docs/application_profile.md) and the documentation on the [Europeana Data Model](https://pro.europeana.eu/resources/standardization-tools/edm-documentation). Here's my understanding of the breakdown of each:

* `cho_edm_type` is for a constrained set of facets
* `cho_type` is for uncontrolled values, likely directly from the metadata itself
* `cho_has_type` is for a to-be-defined set of controlled concepts for types, like your stamp, photo, painting, postcard, etc. example.
