### ISSUE TITLE
Harvest QNL Metadata

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-metadata-old#20]

**Comment by anarchivist** [comment]
Requires QNL to whitelist an IP address; see also sul-dlss/dlme#327

**Comment by jacobthill** [comment]
Harvested data but there currently is no way obvious way of separating data sources as QNL does not use OAI-PMH sets. We have permission only to aggregate the British Library materials. The only way I can think to split these out is by the `physicalLocation` element which indicates the British Library, though further analysis is required to see if this is a reliable option. I have written QNL to ask for a better solution.
