### ISSUE TITLE
Create VM for running harvest and possibly transform scripts

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/dlme-metadata-old#35]
Right now all harvesting, analysis and transform scripts are being run locally on laptops.  We need:

- [x] a new VM with ruby, python and rubygems
- [x] setup appropriate repos (e.g. the new DLME script/havesting repos) to deploy to this VM with capistrano 
- [x] appropriate access to developers

**Comment by jcoyne** [comment]
Given that we are trying to do pass through billing, should this be done on AWS?

**Comment by peetucket** [comment]
Certainly could be done there too.  Only potential challenge (or maybe not) is the requirement that at least one source institution has for whitelisting IPs the machine(s) doing harvesting.  Not sure if this complicates a VM in AWS (are IPs static or at least constrained in a small range?)

**Comment by kamchan** [comment]
The IP could be configured as static. (AWS Elastic IP address)

**Comment by kamchan** [comment]
Looking further into this, since our aws environment is not quite in full automated state (ie puppet/ server backups/ patching etc) for EC2 instances and the timeframe/work to get those pieces into a production ready state is not trivial,   spinning up a VM might be a better choice for this work cycle.

**Comment by justinlittman** [comment]
Also follows pattern of RIALTO.

**Comment by jcoyne** [comment]
@kamchan how are we going to bill CLIR for this?

**Comment by kamchan** [comment]
@julianmorley will have to chime in on that

**Comment by anarchivist** [comment]
For the record, we don't need to bill CLIR, based on what's in the SLA. What we do want to do is to track costs, which I believe @julianmorley suggested we do using resource tagging.

**Comment by peetucket** [comment]
Note that this isn't a blocker for current work, but seems like a good idea medium term (so we don't have jacob perforrming long running harvest tasks on his laptop over his home network).

**Comment by jcoyne** [comment]
On standup yesterday, we agreed that this can be an on premises  VM, and we do not need to do cost tracking for it.

**Comment by kamchan** [comment]
An initial VM (dlme-harvest) is up and running.  Everyone on this workcycle can access this machine via user harvester.

**Comment by kamchan** [comment]
installed python3.4.
