### ISSUE TITLE
Consider approaches for extracting Mets thumbnail urls

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dlme-metadata-old#43]
Doing it at transform time significantly slows down transforms.

**Comment by jcoyne** [comment]
This is why we used to cache these values, so they only happened once.

**Comment by anarchivist** [comment]
Here's an interesting idea - how about if we do the following?

* write a new harvester to fetch from the Met's API, which would allow us to cache and map from the source JSON
* rewrite the Met transform to parse the JSON instead of the CSV

**Comment by anarchivist** [comment]
See sul-dlss/dlme-harvest#11 and sul-dlss/dlme-traject#27
